export type PeopleType = {
  id: number;
  name: string;
  username: string;
  online: boolean;
  imageUrl: string;
};

export const people: PeopleType[] = [
  {
    id: 1,
    name: "Leslie Alexander",
    username: "@l_alexander",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-5.png",
  },
  {
    id: 2,
    name: "Michael Foster",
    username: "@m_foster",
    online: false,
    imageUrl: "/src/assets/tailwind/profile-photo-6.png",
  },
  {
    id: 3,
    name: "Dries Vincent",
    username: "@d_vincent",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-7.png",
  },
  {
    id: 4,
    name: "Lindsay Walton",
    username: "@l_walton",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-8.png",
  },
  {
    id: 5,
    name: "Courtney Henry",
    username: "@c_henry",
    online: false,
    imageUrl: "/src/assets/tailwind/profile-photo-9.png",
  },
  {
    id: 6,
    name: "Tom Cook",
    username: "@t_cook",
    online: false,
    imageUrl: "/src/assets/tailwind/profile-photo.png",
  },
  {
    id: 7,
    name: "Whitney Francis",
    username: "@w_francis",
    online: false,
    imageUrl: "/src/assets/tailwind/profile-photo-4.png",
  },
  {
    id: 8,
    name: "Leonard Krasner",
    username: "@l_krasner",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-2.png",
  },
  {
    id: 9,
    name: "Floyd Miles",
    username: "@f_miles",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-3.png",
  },
  {
    id: 10,
    name: "Emily Selman",
    username: "@e_selman",
    online: false,
    imageUrl: "/src/assets/tailwind/profile-photo-4.png",
  },
  {
    id: 11,
    name: "Kristin Watson",
    username: "@k_watson",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-5.png",
  },
  {
    id: 12,
    name: "Emma Dorsey",
    username: "@e_dorsey",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-6.png",
  },
  {
    id: 13,
    name: "Alicia Bell",
    username: "@a_bell",
    online: false,
    imageUrl: "/src/assets/tailwind/profile-photo-7.png",
  },
  {
    id: 14,
    name: "Jenny Wilson",
    username: "@j_wilson",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-8.png",
  },
  {
    id: 15,
    name: "Anna Roberts",
    username: "@a_roberts",
    online: false,
    imageUrl: "/src/assets/tailwind/profile-photo-9.png",
  },
  {
    id: 16,
    name: "Benjamin Russel",
    username: "@b_russel",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-2.png",
  },
  {
    id: 17,
    name: "Jeffrey Webb",
    username: "@j_webb",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-3.png",
  },
  {
    id: 18,
    name: "Kathryn Murphy",
    username: "@k_murphy",
    online: false,
    imageUrl: "/src/assets/tailwind/profile-photo-4.png",
  },
  {
    id: 19,
    name: "Lawrence Hunter",
    username: "@l_hunter",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-5.png",
  },
  {
    id: 20,
    name: "Yvette Armstrong",
    username: "@y_armstrong",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-6.png",
  },
  {
    id: 21,
    name: "Angela Fisher",
    username: "@a_fisher",
    online: false,
    imageUrl: "/src/assets/tailwind/profile-photo-7.png",
  },
  {
    id: 22,
    name: "Blake Reid",
    username: "@b_reid",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-8.png",
  },
  {
    id: 23,
    name: "Hector Gibbons",
    username: "@h_gibbons",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-9.png",
  },
  {
    id: 24,
    name: "Fabricio Mendes",
    username: "@f_mendes",
    online: false,
    imageUrl: "/src/assets/tailwind/profile-photo-2.png",
  },
  {
    id: 25,
    name: "Jillian Steward",
    username: "@j_steward",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-3.png",
  },
  {
    id: 26,
    name: "Chelsea Hagon",
    username: "@c_hagon",
    online: true,
    imageUrl: "/src/assets/tailwind/profile-photo-4.png",
  },
];
